# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 30

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: false

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - evergreen
  - meta

# Label to use when marking as stale
staleLabel: Awaiting update

# Comment to post when marking as stale. Set to `false` to disable
markComment: |
  Hello! There has been no activity on this issue in the last 30 days. I wonder if it has now been resolved?!

  If you’re reading this, would you mind checking to see if the issue is still applicable?

   * If it has been resolved, please add a message to that effect, and (if you’re able to) close it.
   * If the problem still applies, please add a message to let us know. I’ll remove the "Awaiting update" label, and will check in again next month.

  Thank you!
