name: Move issues to "Awaiting update" column

on:
  issues:
    types:
      - labeled

jobs:
  automate-project-columns:
    if: github.event.label.name == 'awaiting update'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: IATI data bugtracker
          column: Awaiting update
          repo-token: ${{ secrets.GH_TOKEN }}
