name: Mark as updated

on:
  issue_comment:
    types:
      - created

jobs:
  mark-as-updated:
    if: "contains(github.event.issue.labels.*.name, 'awaiting update') && github.event.issue.user.login != 'codeforIATIbot'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "awaiting update"
          github_token: ${{ secrets.GH_TOKEN }}
          fail_on_error: true
