name: Move new issues to "Awaiting triage"

on:
  issues:
    types:
      - opened

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: IATI data bugtracker
          column: Awaiting triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
