name: Move updated issues to "Long-standing issues"

on:
  issues:
    types:
      - unlabeled

jobs:
  automate-project-columns:
    if: github.event.label.name == 'awaiting update'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: IATI data bugtracker
          column: Long-standing issues
          repo-token: ${{ secrets.GITHUB_TOKEN }}
